spring:
    application:
        name: hh-bot
    datasource:
        url: jdbc:h2:mem:hhbot_db
        username: sa
        password: 123
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    output:
        ansi:
            enabled: always